List<String> kAtoll = [
  "Select Island",
  "Aarah",
  "Akirifushi",
  "Asdhoo",
  "Baros",
  "Biyaadhoo",
  "Boduban'dos",
  "Bodufinolhu",
  "Boduhithi",
  "Boduhuraa",
  "Bolifushi",
  "Dhiffushi",
  "Dhigufinolhu",
  "Dhoonidhoo",
  "En'boodhoo",
  "En'boodhoofinolhu",
  "Eriadhoo",
  "Erruh-huraa",
  "Farukolhufushi",
  "Feydhoofinolhu",
  "Fihaalhohi",
  "Fonadhoo",
  "Furanafushi",
  "Gaafaru",
  "Gaagan'du",
  "Gashurifinolhu",
  "Giraavaru",
  "Girifushi",
  "Gulhi",
  "Gulhigaathuhuraa",
  "Guraidhoo",
  "Helen'geli",
  "Henbadhoo",
  "Hinmafushi",
  "Hulhule",
  "Hulhumale'",
  "Huraa",
  "Ihuru",
  "Kaashidhoo",
  "Kagi",
  "Kalhuhuraa",
  "Kan'doomaafushi",
  "Kan'duoiygiri",
  "Kanifinolhu",
  "Kanuoiyhuraa",
  "Kohdhipparu",
  "Kudaban'dos",
  "Kudafinolhu",
  "Kudahithi",
  "Kudahuraa",
  "Lankanfinolhu",
  "Lankanfushi",
  "Lhohifushi",
  "Lhosfushi",
  "Maadhoo",
  "Maafushi",
  "Madivaru",
  "Mahaana elhihuraa",
  "Maifalhuhuraa",
  "Makundhoo",
  "Makunufushi",
  "Male",
  "Maniyafushi",
  "Medhufinolhu",
  "Meerufenfushi",
  "Nakahchaafushi",
  "Olhigan'dufinolhu",
  "Olhuhali",
  "Olhuveli",
  "Rannaalhi",
  "Rasfari",
  "Than'burudhoo",
  "Thilafushi",
  "Thulhaagiri",
  "Thulusdhoo",
  "Huraagan'du",
  "Thun'bafushi",
  "Vaadhoo",
  "Vaagali",
  "Vabbinfaru",
  "Vabboahuraa",
  "Vahmaafushi",
  "Velassar",
  "Veligan'duhuraa",
  "Vihamanaafushi",
  "Vilin'gili mathidhahuraa",
  "Vilingili",
  "Vilivaru",
  "Ziyaaraiyfushi",
  "Udhafinolhu",
  "Dhonmaaga",
  "Bulhifushi",
  "Funfinolhu",
  "Noofinolhu",
  "Emmafushi",
  "Akasdhoo",
  "Aanugan'du huraa",
];

List<String> hiAtoll = [
  "Select Island",
  "Alidhoo",
  "Alidhuffarufinolhu",
  "Baarah",
  "Beenaafushi",
  "Berinmadhoo",
  "Dhapparuhuraa",
  "Dhihdhoo",
  "Dhonakulhi",
  "Filladhoo",
  "Gaamathikulhudhoo",
  "Gallandhoo",
  "Govvaafushi",
  "Hathifushi",
  "Huvahandhoo",
  "Huvarafushi",
  "Ihavandhoo",
  "Innafinolh",
  "Kan'daalifinolhu",
  "Kelaa",
  "Kudafinolhu",
  "Maafahi",
  "Maafinolhu",
  "Maarandhoo",
  "Maarandhoofarufinolhu",
  "Madulu",
  "Manafaru",
  "Matheerah",
  "Medhafushi",
  "Mulhadhoo",
  "Mulidhoo",
  "Muraidhoo",
  "Naridhoo",
  "Thakandhoo",
  "Thuraakunu",
  "Uligamu",
  "Un'gulifinolhu",
  "Utheemu",
  "Van'gaaru",
  "Vashafaru",
  "Velifinolhu",
];

List<String> hdAtoll = [
  "Select Island",
  "Dhipparufushi",
  "Faridhoo",
  "Fenboahuraa",
  "Finey",
  "Hanimaadhoo",
  "Hirimaradhoo",
  "Hirinaidhoo",
  "Hon'daafushi",
  "Hon'daidhoo",
  "Innafushi",
  "Kanamana",
  "Kattalafushi",
  "Keylakunu",
  "Kudafarufasgandu",
  "Kudamuraidhoo",
  "Kulhudhuffushi",
  "Kumundhoo",
  "Kun'burudhoo",
  "Kurin'bee",
  "Maavaidhoo",
  "Makunudhoo",
  "Muiri",
  "Naagoashi",
  "Naivaadhoo",
  "Nellaidhoo",
  "Neykurendhoo",
  "Nolhivaramu",
  "Nolhivaranfaru",
  "Ruffushi",
  "Theefaridhoo",
  "Vaikaradhoo",
  "Vaikaramuraidhoo",
  "Veligan'du",
  "Kuredhigadu",
];

List<String> shAtoll = [
  "Select Island",
  "Bileiyfahi",
  "Bis alhaahuraa",
  "Boduhuraa",
  "Bolissafaru",
  "Dhigurah",
  "Dholhiyadhoo",
  "Dholhiyadhookudarah",
  "Dhonvelihuraa",
  "Ekasdhoo",
  "Eriadhoo",
  "Farukolhu",
  "Feevah",
  "Feydhoo",
  "Firubaidhoo",
  "Foakaidhoo",
  "Funadhoo",
  "Fushifaru",
  "Gaakoshibi",
  "Gallaidhoo",
  "Goidhoo",
  "Gonaafarufinolhu",
  "Horubadhoo",
  "Hurasfaru",
  "Kakaa eriyadhoo",
  "Kan'baalifaru",
  "Kan'ditheem",
  "Keekimini",
  "Komandoo",
  "Kudadhoo",
  "Kudafarufinolhu",
  "Kudalhaimendhoo",
  "Lhaimagu",
  "Maakan'doodhoo",
  "Maaun'goodhoo",
  "Madidhoo",
  "Madikurehdhoo",
  "Mairah",
  "Maroshi",
  "Mathi Komandoo",
  "Medhukun'burudhoo",
  "Medhurah",
  "Migoodhoo",
  "Milandhoo",
  "Naainfarufinolhu",
  "Naalaahuraa",
  "Nalandhoo",
  "Narudhoo",
  "Narurin'budhoo",
  "Neyo",
  "Noomaraa",
  "Raggan'duhuraa",
  "Vagaru",
  "Naainfaru",
];

List<String> nAtoll = [
  "Select Island",
  "Ban'daidhidhdhoo",
  "Bodufushi",
  "Bodulhaimendhoo",
  "Kalaidhoo",
  "Burehifasdhoo",
  "Dheefuram",
  "Dhekenanfaru",
  "Dhelibe ruh elhihuraa",
  "Dhigurah",
  "Dhonaeri kan'doodhoo",
  "Ehdhuffaru mairah",
  "Ekulhivaru",
  "Farumuli",
  "Felivaru",
  "Fohdhipparu",
  "Fohdhoo",
  "Orimasvaru",
  "Goan'bilivaadhoo",
  "Hen'badhoo",
  "Holhudhoo",
  "Holhumeedhoo",
  "Huivani",
  "Hulhuhdhoo",
  "Huvan'dhumaavattaru",
  "In'guraidhoo",
  "Kaalhugemendhoo",
  "Kafa Komandoo",
  "Bomasdhoo",
  "Kan'dinmaahuraa",
  "Karinma",
  "Karinmavattaru",
  "Kendhivaru",
  "Ken'dhikulhudhoo",
  "Kudafari",
  "Kudafunafaru",
  "Kudafushi",
  "Kunnumala",
  "Kuramaadhoo",
  "Kuredhivaru",
  "Landhoo",
  "Lhohi",
  "Loafaru",
  "Maafaru",
  "Maafunafaru",
  "Maakanaafushi",
  "Maakurehdhoo",
  "Maalhendhoo",
  "Maavahdhoo",
  "Maavelavaru",
  "Magoodhoo",
  "Manadhoo",
  "Medhafushi",
  "Medhufaru",
  "Miladhoo",
  "Minaavaru",
  "Fushivelavaru",
  "Orivaru",
  "Orivarukudarah",
  "Raafushi",
  "Raalhulaakolhu",
  "Randheli",
  "Than'burudhoo",
  "Than'burudhuffushi",
  "Tholhendhoo",
  "Thoshigan'dukolhu",
  "Vavathi",
  "Velidhoo",
  "Vihafarufinolhu",
];

List<String> rAtoll = [
  "Select Island",
  "Aarah",
  "Alifushi",
  "Angaagiri",
  "An'golhitheemu",
  "Arilundhoo",
  "Ban'daveri",
  "Bodufarufinolhu",
  "Bodufen maaen'budhoo",
  "Bodufushi",
  "Boduhaiykodi",
  "Boduhuraa",
  "Dheburidheythereyvaadhoo",
  "Dhekunumaafaru",
  "Dhigali",
  "Dhikkurehdhoo",
  "Dhinnaafushi",
  "Dhoragali",
  "Dhuvaafaru",
  "Dhuvaafaruhuraa",
  "Ethigan'du jehihuraa",
  "Ehthigili",
  "Faarufushi",
  "Fainu",
  "Fasgan'dufaru",
  "Fasmendhoo",
  "Fenfushi",
  "Filaidhoo",
  "Fuggiri",
  "Furaveri",
  "Gaaun'doodhoo",
  "Giraavar",
  "Goboshi",
  "Goiymaru",
  "Goyyafaru",
  "Hiboodhoo",
  "Hiraveri",
  "Hulhudhoo",
  "Hulhudhuffaaru",
  "Huruvalhi",
  "Ifuru",
  "In'guraidhoo",
  "Innamaadhoo",
  "Kan'dholhudoo",
  "Kandhoomeehunge lhaan'bugali",
  "Kan'doogan'du",
  "Kinolhas",
  "Kothaifaru",
  "Kottefaru",
  "Kudafen maaen'boodhoo",
  "Kudafushi",
  "Kudakurathu",
  "Kudalhosgiri",
  "Kudathulhaadhoo",
  "Kukulhudhoo",
  "Kurehdhoo",
  "Kuroshigiri",
  "Lhaan'bugali",
  "Lhohi",
  "Lin'boakandhoo",
  "Lun'dhufushi",
  "Maakurathu",
  "Maamin'gili",
  "Maamunagau",
  "Maamunagaufinolhu",
  "Maanenfushi",
  "Maashigiri",
  "Madivaafaru",
  "Maduvvari",
  "Mahidhoo",
  "Meedhoo",
  "Meedhuppar",
  "Mullaafushi",
  "Muravandhoo",
  "Neyo",
  "Rasgetheemu",
  "Rasmaadhoo",
  "Thaavathaa",
  "Ufulandhoo",
  "Un'goofaaru",
  "Un'gulu",
  "Uthurumaafaru",
  "Vaadhoo",
  "Vaffushi",
  "Vaffushihuraa",
  "Vandhoo",
  "Veyvah",
  "Vilin'gili",
  "Gemana",
  "Orimasfushi",
];

List<String> bAtoll = [
  "Select Island",
  "Ahivaffushi",
  "Aidhoo",
  "Anhenunfushi",
  "Bathalaa",
  "Boadhaafushifinolhu",
  "Bodufinolhu",
  "Boifushi",
  "Dhakandhoo",
  "Dhandhoo",
  "Dharavandhoo",
  "Dhashufaruhuraa",
  "Dhigudhefaru",
  "Dhigufaruvinagan'du",
  "Dhonfanu",
  "Dhoogan'dufinolhu",
  "Dhunikolhu",
  "En'boodhoo",
  "Eydhafushi",
  "Fares",
  "Fehendhoo",
  "Finolhas",
  "Fonimagoodhoo",
  "Fulhadhoo",
  "Funadhoo",
  "Gaagan'dufaruhuraa",
  "Gaavilin'gili",
  "Gemendhoo",
  "Goidhoo",
  "Hanifaru",
  "Hanifaruhuraa",
  "Hibalhidhoo",
  "Hirundhoo",
  "Hithaadhoo",
  "Horubadhoo",
  "Hulhudhoo",
  "Maaddoo Hulhudhoo",
  "Innafushi",
  "Kamadhoo",
  "Kanufusheegaathufinolhu",
  "Kanufushi",
  "Kashidhoo",
  "Kashidhuffarufinolhu",
  "Kendhoo",
  "Keyodhoo",
  "Kihaadhoo",
  "Kihaadhuffaru",
  "Kihavah huravalhi",
  "Kudadhoo",
  "Kudarikilu",
  "Kunfunadhoo",
  "Lan'daagiraavaru",
  "Maaddoo",
  "Maalhos",
  "Maamaduvvari",
  "Maarikilu",
  "Madhirivaadhoo",
  "Mathifaru",
  "Medhufinolhu gaathufinolhu",
  "Mendhoo",
  "Milaidhoo",
  "Miriandhoo",
  "Muhdhoo",
  "Muthaafushi",
  "Nelivarufinolh",
  "Nibiligaa",
  "Olhugiri",
  "Thiladhoo",
  "Thulhaadhoo",
  "Ufuligiri",
  "Un'doodhoo",
  "Vakkaru",
  "Velavaru",
  "Veyofushi",
  "Vinaneiyfaruhuraa",
  "Voavah",
  "Huraafaru",
];

List<String> lhAtoll = [
  "Select Island",
  "Aligaa",
  "Boamandhipparu huraagan'du",
  "Bodufinolhu",
  "Bodugaahuraa",
  "Dhashugiri Finolhu",
  "Dheruffinolhu",
  "Dhihdhoo",
  "Dhiffushi",
  "Dhirun'baahura",
  "Faadhoo",
  "Faadhoohuraagan'du",
  "Fainu aadhanhuraa",
  "Fehigili",
  "Fushifaru",
  "Gaaerifaru",
  "Govvaafushi",
  "Hinnavaru",
  "Hiriyaadhoo",
  "Hudhufushi",
  "Huravalhi",
  "Innahuraa",
  "Kalhumanjehuraa",
  "Kanifushi",
  "Kanuhuraa",
  "Komandoo",
  "Kudadhoo",
  "Kurehdhoo",
  "Kurendhoo",
  "Lhohi",
  "Lhossalafushi",
  "Maabinhuraaa",
  "Maafilaafushi",
  "Maakoa",
  "Madhiriguraidhoo",
  "Madivaru",
  "Maduvvari",
  "Maidhoo",
  "Mas leggihuraa",
  "Medha adihuraa",
  "Medhafushi",
  "Meedhaahuraa",
  "Meyyafushi",
  "Naifaru",
  "Olhuvelifushi",
  "Ookolhufinolhu",
  "Rathuruh-huraa",
  "Sellhifushi",
  "Thilamaafushi",
  "Varihuraa",
  "Vavvaru",
  "Veligan'du",
  "Veyvah",
  "Vihafarufinolhu",
];

List<String> iiAtoll = [
  "Select Island",
  "Alikoirah",
  "Bathalaa",
  "Bodufolhudhoo",
  "Ellaidhoo",
  "Etheremadivaru",
  "Feridhoo",
  "Fesdhoo",
  "Fusfinolhu",
  "Fushi",
  "Gaagan'du",
  "Gaathafushi",
  "Gangehi",
  "Halaveli",
  "Himendhoo",
  "Kan'dholhudoo",
  "Kudafolhudhoo",
  "Kuramathi",
  "Maagau",
  "Maalhos",
  "Maayafushi",
  "Madivaru",
  "Madivarufinolhu",
  "Madoogali",
  "Mathivereefinolhu",
  "Mathiveri",
  "Mushimasmigili",
  "Rasdhoo",
  "Thoddoo",
  "Ukulha",
  "Velidhoo",
  "Veligan'du",
  "Vihamaafaru",
];

List<String> idAtoll = [
  "Select Island",
  "Angaagau",
  "Ariyadhoo",
  "Athurugau",
  "Bodufinolhu",
  "Bodukaashihuraa",
  "Bulhalohi",
  "Dhan'gethi",
  "Dhihdhoo",
  "Dhihdhoofinolhu",
  "Dhiffushi",
  "Dhiggiri",
  "Dhigurah",
  "En'boodhoo",
  "Fenfushi",
  "Fushidhigga",
  "Hangnaameedhoo",
  "Heenfaru",
  "Hiyafushi",
  "Hukurudhoo",
  "Hurasdhoo",
  "Huruelhi",
  "Huvahendhoo",
  "Innafushi",
  "Kalhahan'dhihuraa",
  "Kudadhoo",
  "Kudarah",
  "Kun'burudhoo",
  "Lonuboi",
  "Maafushivaru",
  "Maamin'gili",
  "Machchafushi",
  "Mahibadhoo",
  "Mandhoo",
  "Mirihi",
  "Moofushi",
  "Nalaguraidhoo",
  "Omadhoo",
  "Rangaleefinolhu",
  "Rangal",
  "Theluveligaa",
  "Tholhifushi",
  "Thun'dufushi",
  "Vakarufalhi",
  "Vilamendhoo",
  "Vilin'gilivaru",
  "Rahdhiggaa",
];

List<String> vAtoll = [
  "Select Island",
  "Aarah",
  "Alimathaa",
  "Anbaraa",
  "Bodumohoraa",
  "Dhiggiri",
  "Felidhoo",
  "Fohtheyobodufushi",
  "Fulidhoo",
  "Hin'gaakulheefinolhu",
  "Hulhidhoo",
  "Keyodhoo",
  "Kuda anbaraa",
  "Kunaavashi",
  "Rakeedhoo",
  "Ruh hurihuraa",
  "Thinadhoo",
  "Thun'duhuraa",
  "Vashugiri",
  "Vattaru",
];

List<String> mAtoll = [
  "Select Island",
  "Boahuraa",
  "Dhekunuboduveli",
  "Dhiggaru",
  "Dhihthun'di",
  "Erruh-huraa",
  "Fenfuraaveli",
  "Gaakurali",
  "Gasveli",
  "Gongalihuraa",
  "Hakuraahuraa",
  "Hudhuveli",
  "Hurasveli",
  "Kekuraalhuveli",
  "Kolhufush",
  "Kuda usfushi",
  "Kuradhigan'du",
  "Maa usfushi",
  "Maahuraa",
  "Maalhaveli",
  "Madifushi",
  "Maduvvari",
  "Medhufushi",
  "Mulah",
  "Muli",
  "Naalaafushi",
  "Raaban'dhihuraa",
  "Raiymandhoo",
  "Seedheehuraa",
  "Seedheehuraa veligan'du",
  "Thuvaru",
  "Uthuruboduveli",
  "Uthurugaseveli",
  "Veyvah",
];

List<String> fAtoll = [
  "Select Island",
  "Adhangau",
  "Bileiydhoo",
  "Dharan'boodhoo",
  "Dhiguvarufinolhu",
  "En'bulufushi",
  "Faanumaahuraa",
  "Feeali",
  "Filitheyo",
  "Himithi",
  "Jinnathugau",
  "Kan'dumoonufushi",
  "Maafushi",
  "Madivaruhuraa",
  "Magoodhoo",
  "Magoodhoo bodufinolhu",
  "Makunueri",
  "Minimasgali",
  "Nilandhoo",
  "Vilin'gilivaru Finolhu",
];

List<String> dAtoll = [
  "Select Island",
  "Aluvifushi",
  "Ayyakaloahuraa",
  "Angalhaidhoo",
  "Aarah",
  "Ban'didhoo",
  "Bulhalafushi",
  "Dhebaidhoo",
  "Dhoores",
  "En'boodhoofushi",
  "Faandhoo",
  "Fenfushi",
  "Fenmeeruhuraa",
  "Gemendhoo",
  "Hiriyafushi",
  "Hudhufusheefinolhu",
  "Hulhudheli",
  "Hulhuvehi",
  "Issari",
  "Kan'dinmaa",
  "Kanneiyfaru",
  "Kedhigan'du",
  "Kiraidhoo",
  "Kudahuvadhoo",
  "Lhohi",
  "Maadheli",
  "Maaen'boodhoo",
  "Maafushi",
  "Maagau",
  "Maalefaru",
  "Meedhoo",
  "Meedhuffushi",
  "Minimasgali",
  "Olhufushi",
  "Olhuveli",
  "Rin'budhoo",
  "Thaban'lhaidhoo",
  "Thilabolhufushi",
  "Thinhuraa",
  "Uhdhoo",
  "Vaanee",
  "Valla",
  "Vallalhohi",
  "Velavaru",
  "Vommuli",
];

List<String> thAtoll = [
  "Select Island",
  "Bodufinolhu",
  "Bodurehaa",
  "Burunee",
  "Dhiffushi",
  "Dhiyamigili",
  "Dhonanfushi",
  "Dhururehaa",
  "Ekuruffushi",
  "Elaa",
  "Fenfushi",
  "Fenmeerufushi",
  "Fondhoo",
  "Fonidhaani",
  "Funaddu",
  "Fushi",
  "Gaadhiffushi",
  "Gaalee",
  "Gaathurehaa",
  "Guraidhoo",
  "Hathifushi",
  "Hikan'dhihohi",
  "Hirilandhoo",
  "Hiriyanfushi",
  "Hon'delifushi",
  "Hulhiyanfushi",
  "Kaaddoo",
  "Kafidhoo",
  "Kakolhas",
  "Kalhufahalafushi",
  "Kan'doodhoo",
  "Kan'dufushi",
  "Kani",
  "Kanimeedhoo",
  "Kin'bidhoo",
  "Kolafushi",
  "Kolhufushi",
  "Kudadhoo",
  "Kudakaaddoo",
  "Kudakin'bidhoo",
  "Kuran'dhuvaru",
  "Kuredhifushi",
  "Lhavaddoo",
  "Maagulhi",
  "Maalefushi",
  "Madifushi",
  "Mathidhoo",
  "Medhafushi",
  "Olhudhiyafushi",
  "Olhufushi",
  "Olhufushifinolhu",
  "Olhugiri",
  "Omadhoo",
  "Rihaamaafushi",
  "Ruhthibirah",
  "Thimarafushi",
  "Ufuriyaa",
  "Usfushi",
  "Vanbadhi",
  "Vandhoo",
  "Veymandoo",
  "Vilufushi",
  "Kalhudheyfushi",
];

List<String> lAtoll = [
  "Select Island",
  "Aarahaa",
  "Athahendha",
  "Baresdhoo",
  "Bodu mungnafushi",
  "Bodufenrahaa",
  "Bodufinolhu",
  "Boduhuraa",
  "Bodumaabulhali",
  "Bodumahigulhi",
  "Bokaiyfushi",
  "Burrahaa",
  "Dhan'bidhoo",
  "Dhonberahaa",
  "Enberahaa",
  "Fares",
  "Fenboarahaa",
  "Fenboahuraa",
  "Fonadhoo",
  "Fonagaadhoo",
  "Fushi",
  "Gaadhoo",
  "Gan",
  "Gahagan'dufinolhu",
  "Guraidhoo",
  "Haiythoshi",
  "Hanhushi",
  "Hedha",
  "Hikan'dhirahaa",
  "Hithadhoo",
  "Holhurahaa",
  "Hulhimendhoo",
  "Hulhiyandhoo",
  "Hulhisdhoo",
  "Boduhuraa",
  "Isdhoo",
  "Kahdhoo",
  "Kalhaidhoo",
  "Kalhurahaa",
  "Kandaru",
  "Kanuhuraa",
  "Kashidhoo",
  "Kokurahaa",
  "Kuda munyafushi",
  "Kudafares",
  "Kudafenrehaa",
  "Kudafushi",
  "Kudamaabulhali",
  "Kudarah",
  "Kudaveshi",
  "Kunahandhoo",
  "Kuredhirehaa",
  "Maabaidhoo",
  "Maafushi",
  "Maakalhuveli",
  "Maamendhoo",
  "Maandho",
  "Maavah",
  "Maaveshi",
  "Mahakanfushi",
  "Medhu vinagan'du",
  "Mendhoo",
  "Mundoo",
  "Olhutholhu",
  "Olhuveli",
  "Rahaa",
  "Thathunrahaa",
  "Thun'buri",
  "Uthuru vinagan'du",
  "Uvadhevifushi",
  "Vadinolhu",
  "Veligan'dufinolhu",
  "Dhekunuvinagan'du",
];

List<String> giAtoll = [
  "Select Island",
  "Araigaththaa",
  "Baavanadhoo",
  "Bakeththaa",
  "Beyrumauddoo",
  "Bihurehaa",
  "Boadduvaa",
  "Bodufuttaa",
  "Bodubon'deyyaa",
  "Bodufinolhu",
  "Boduhuraa",
  "Dhaandhoo",
  "Dhevvaamaagala",
  "Dhevvadhoo",
  "Dhevvalaabadhoo",
  "Dhigudhoo",
  "Dhigurah",
  "Dhiyadhoo",
  "Falhumaafushi",
  "Falhuverrahaa",
  "Fulhadhoo",
  "Fenehutta",
  "Fenrehaa",
  "Fulan'gi",
  "Funadhoo",
  "Funadhooviligillaa",
  "Funamauddaa",
  "Galandhoo",
  "Gemanafushi",
  "Han'dahaa",
  "Hinaamaagalaa",
  "Hirihuttaa",
  "Hithaadhoo",
  "Hithaadhoogalaa",
  "Hulhimendhoo",
  "Hurendhoo",
  "Idhimaa",
  "Innarehaa",
  "Kalhehuttaa",
  "Kaludirehaa",
  "Kan'duhulhudhoo",
  "Kan'duvilin'gili",
  "Kendheraa",
  "Kerehdhoo",
  "Kisserahaa",
  "Kodagehuttaa",
  "Kodahuttaa",
  "Kodeymatheelaabadhoo",
  "Kodeyvilin'gili",
  "Kolamaafushi",
  "Kon'dey",
  "Kooddoo",
  "Kudalafari",
  "Lhossaa",
  "Hagevilla",
  "Maafehelaa",
  "Maagihuttaa",
  "Maakanaarataa",
  "Maamendhoo",
  "Maamutaa",
  "Maarandhoo",
  "Maarehaa",
  "Mahahdhoo",
  "Mahthidhoo",
  "Mahthurehaa",
  "Maanaagala",
  "Medharehaa",
  "Medhehuttaa",
  "Medhuburiyaa",
  "Melaimu",
  "Meradhoo",
  "Minimessa",
  "Munandhuvaa",
  "Nilandhoo",
  "Odagallaa",
  "Raaverrehaa",
  "Vilin'gili",
  "Vodamulaa",
  "Ribidhoo",
  "Baberahutt",
  "Villigalaa",
  "Kun'bumaafushi",
  "Kudhebondeyyaa",
];

List<String> gdAtoll = [
  "Select Island",
  "Baulhagallaa",
  "Bodehutta",
  "Boduhuttaa",
  "Bodurehaa",
  "Dhekaamba",
  "Dheruke'rehaa",
  "Dhigelaabadhuvaa",
  "Dhigurehaa",
  "Dhoonirehaa",
  "Dhoonirehaa",
  "Ehivakaa",
  "Ekelondaa",
  "Farehulhedhoo",
  "Faresmaathodaa",
  "Farukolhuhuttaa",
  "Femunaidhoo",
  "Fenevenehuttaa",
  "Fiyoari",
  "Gahdhoo",
  "Velagalaa",
  "Gan",
  "Gazeeraa",
  "Golhaallaa",
  "Gosi",
  "Havoddaa",
  "Havodigalaa",
  "Hevaahulhadhoo",
  "Hoan'dehdoo",
  "Hoothodeyaa",
  "Hulhuvaarulaa",
  "Hunigon'direhaa",
  "Kaadehdhoo",
  "Kaalhehuttaa - fiyoari falhuthere",
  "Kaalhehuttaa - Farehu falhuthere",
  "Kaashidhoo",
  "Kaashihulhudhoo",
  "Kadevaareha",
  "Kudhefalaa",
  "Kafena",
  "Kalhahigillaa",
  "Kalhahuttaa",
  "Kalhehamalaa",
  "Kanandhuvaa",
  "Kan'dahalagalaa",
  "Kannigillaa",
  "Kelaihuttaa",
  "Keramihthaa",
  "Neimaahutta",
  "Kodaanahutta",
  "Kodahutigalaa, Maahutigalaa, Maaodagalaa",
  "Kodedhoo",
  "Kodegalaa",
  "Koderataa",
  "Konottaa",
  "Kudhehulhehdhoo",
  "Kudhelifadhoo",
  "Kudhemaaneidhoo",
  "Kudherataa",
  "Laihaa",
  "Lonudhoo",
  "Lonudhoohuttaa",
  "Maaehivakaa",
  "Maagalaa",
  "Maagon'derehaa",
  "Maallaarehaa",
  "Maarehaa",
  "Maavaarulu",
  "Maavahdhuva",
  "Madaveli",
  "Maguhdhuvaa",
  "Mathaidhuvaa",
  "Mathihutta",
  "Mathikeranahuttaa",
  "Meehunthibenehuttaa",
  "Menthandhuvaa",
  "Meregihutaa",
  "Meyragillaa",
  "Bodehutta",
  "Mudhimaahutta",
  "Nadellaa",
  "Odagallaa",
  "Olhimuttaa",
  "Olhurataa",
  "Rahadhuvaa",
  "Rathafandhoo",
  "Thelehuttaa",
  "Thinadhoo",
  "Thinahuttaa",
  "Uhehuttaa",
  "Ukurihuttaa",
  "Ulegalaa",
  "Vaadhoo",
  "Vaireyaadhuvaa",
  "Vatavarrehaa",
  "Veraaviligillaa",
  "Vilin'gillaa",
  "Rondaadhuvaa",
  "Hakandho",
  "Hadaadho",
  "Haveyyarata",
  "Haadhuva",
  "Raabadaafehiratt",
  "Kaafarata",
  "Kandahdho",
  "Kalhereha",
  "Kudhehaadhuva",
  "Kudhebeerahutt",
  "Kudhemathaidhuva",
  "Athihutta",
  "Aakiraahutta",
  "Ekurukaarata",
  "Maarehaa",
  "Fare'dho",
  "Faahutta",
  "Faanahutta",
  "Fereythavilligilla",
  "Dhate'keraanahutt",
  "Dhate'mulaidho",
  "Dhimmana",
  "Lifadho",
  "Dhiyanigill",
  "Oinigilla",
  "Dhoonirehaa",
  "Kurikeymaahutt",
];

List<String> gnAtoll = [
  "Select Island",
  "Fuvahmulah",
];

List<String> sAtoll = [
  "Select Island",
  "Aboohuraa",
  "Bedhey aurah",
  "Boduhajara",
  "Dheeron'di",
  "Dhigiheraa",
  "Fathikedeheragadu",
  "Feydhoo",
  "Gan",
  "Gauken'di",
  "Geskalhaheraa",
  "Gomahera",
  "Hankede",
  "Herethere",
  "Hikahera",
  "Hithadhoo",
  "Hulhudhoo",
  "Kan'dihera gan'du",
  "Koahera",
  "Ismehelahera",
  "Kodadhihera gan'du",
  "Kudamaahera",
  "Maahera",
  "Maradhoo",
  "Maradhoofeydhoo",
  "Meedhoo",
  "Mulikede",
  "Savaaheli",
  "Vilin'gili",
  "Hasanbeaarah",
  "Kudhehera",
  "Kudahajara",
  "Kedevaahera",
];

List<String> getIslandList(String atoll) {
  switch (atoll) {
    case "Kaafu Atoll":
      return kAtoll;
    case "HAA ALIFU ATOLL":
      return hiAtoll;
    case "HAA DHAALU ATOLL":
      return hdAtoll;
    case "SHAVIYANI ATOLL":
      return shAtoll;
    case "NOONU ATOLL":
      return nAtoll;
    case "RAA ATOLL":
      return rAtoll;
    case "BAA ATOLL":
      return bAtoll;
    case "LHAVIYANI ATOLL":
      return lhAtoll;
    case "ALIFU ALIFU ATOLL":
      return iiAtoll;
    case "ALIFU DHAALU ATOLL":
      return idAtoll;
    case "VAAVU ATOLL":
      return vAtoll;
    case "MEEMU ATOLL":
      return mAtoll;
    case "FAAFU ATOLL":
      return fAtoll;
    case "DHAALU ATOLL":
      return dAtoll;
    case "THAA ATOLL":
      return dAtoll;
    case "LAAMU ATOLL":
      return lAtoll;
    case "GAAFU ALIFU ATOLL":
      return giAtoll;
    case "GAAFU DHAALU ATOLL":
      return gdAtoll;
    case "GNAVIYANI ATOLL":
      return gnAtoll;
    case "SEENU ATOLL":
      return sAtoll;
    default:
      return ['Select Island'];
  }
}

List<String> atolls = [
  "Select Atoll",
  "Kaafu Atoll",
  "HAA ALIFU ATOLL",
  "HAA DHAALU ATOLL",
  "SHAVIYANI ATOLL",
  "NOONU ATOLL",
  "RAA ATOLL",
  "BAA ATOLL",
  "LHAVIYANI ATOLL",
  "ALIFU ALIFU ATOLL",
  "ALIFU DHAALU ATOLL",
  "VAAVU ATOLL",
  "MEEMU ATOLL",
  "FAAFU ATOLL",
  "DHAALU ATOLL",
  "THAA ATOLL",
  "LAAMU ATOLL",
  "GAAFU ALIFU ATOLL",
  "GAAFU DHAALU ATOLL",
  "GNAVIYANI ATOLL",
  "SEENU ATOLL",
];
